AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  ExampleFunc:
    Type: "AWS::Serverless::Function"
    Properties:
      Handler: handler_name_doesnt_matter
      Runtime: provided
      CodeUri: ./rust.zip
      Events:
        Index:
          Type: Api
          Properties:
            Path: /
            Method: get
            RestApiId: MyApi
        # There doesn't seem to be a way to define a proxy endpoint...

  MyApi:
    Type: "AWS::Serverless::Api"
    Properties:
      StageName: default
      BinaryMediaTypes:
        - image~1png
